export interface Product {
  id: string;
  category: number; // 0: Parafusos, 1: Porcas, 2: Arruelas, 3: Chumbadores Mecânicos, 4: Chumbadores Químicos, 5: Rebites, 6: Fixadores Para Painéis Solares, 7: Acessórios e Fixadores, 8: Barras Roscadas
  title: string;
  norm: string;
  material: string;
  grade: string;
  application: string;
  description: string;
  sizes: string[];
  image: string; // Caminho da imagem, ex: "/images/produtos/parafuso-a325.jpg"
}

export const productsData: Product[] = [
  // Categoria 0: Parafusos
  {
    id: "parafuso-1",
    category: 0,
    title: "Parafuso Francês",
    norm: "DIN 603 / ASME B18.5",
    material: "Aço Carbono / Inox",
    grade: "Classe 4.6 / 8.8",
    application: "Fixação de madeira em metal, carrocerias, divisórias e suportes.",
    description: "Cabeça de cogumelo sem fenda com pescoço quadrado auto-travante.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\"", "M6", "M8", "M10", "M12"],
    image: "/produtos/parafuso-frances.jpeg",
  },
  {
    id: "parafuso-2",
    category: 0,
    title: "Parafuso Sextavado",
    norm: "DIN 931 / DIN 933 / ISO 4014 / ISO 4017",
    material: "Aço Carbono, Liga e Inox",
    grade: "Classe 5.8 / 8.8 / 10.9 / 12.9",
    application: "União e fixação de elementos mecânicos e estruturas metálicas em geral.",
    description: "Parafusos sextavados padrão com rosca parcial ou inteira.",
    sizes: ["M6", "M8", "M10", "M12", "M16", "M20", "M24", "1/4\"", "1/2\"", "3/4\""],
    image: "/produtos/parafuso-sextavado.jpeg",
  },
  {
    id: "parafuso-3",
    category: 0,
    title: "Parafuso Sextavado Interno (Cabeça Cilíndrica)",
    norm: "DIN 912 / ISO 4762",
    material: "Aço Liga de Alta Resistência / Inox",
    grade: "Classe 12.9 / Inox A2",
    application: "Maquinários de precisão, matrizes e motores.",
    description: "Cabeça cilíndrica com sextavado interno para aperto de torque elevado.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10", "M12", "M16", "M20"],
    image: "/produtos/parafuso_sextavado_interno_-cabeca_cilindrica-.jpeg",
  },
  {
    id: "parafuso-4",
    category: 0,
    title: "Parafuso ASTM A325",
    norm: "ASTM A325 / ASME B18.2.6",
    material: "Aço Carbono Temperado e Revenido",
    grade: "Classe A325 Tipo 1",
    application: "Ligações estruturais pesadas, flanges de pontes e galpões metálicos.",
    description: "Projetado para resistir a altas cargas de tração e cisalhamento.",
    sizes: ["1/2\"", "5/8\"", "3/4\"", "7/8\"", "1\"", "1.1/4\""],
    image: "/produtos/parafuso_astm_a325.png",
  },
  {
    id: "parafuso-5",
    category: 0,
    title: "Parafuso Sextavado (Flangeado DIN 6921)",
    norm: "DIN 6921 / EN 1665",
    material: "Aço Carbono e Liga",
    grade: "Classe 8.8 / 10.9",
    application: "Montagens industriais e automotivas sujeitas a vibração.",
    description: "Flange integrada sob a cabeça que distribui a pressão e dispensa arruela lisa.",
    sizes: ["M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/parafuso_sextavado_-flangeado_din_6921-.png",
  },
  {
    id: "parafuso-6",
    category: 0,
    title: "Parafuso Cabeça Sextavada (Rosca Soberba)",
    norm: "DIN 571",
    material: "Aço Carbono Zincado / Inox",
    grade: "Grau Comercial",
    application: "Fixação em madeira, buchas de nylon em paredes de alvenaria e concreto.",
    description: "Rosca soberba autocortante para excelente fixação e ancoragem.",
    sizes: ["3/16\"", "1/4\"", "5/16\"", "3/8\"", "1/2\""],
    image: "/produtos/parafuso_cabeca_sextavada_-rosca_soberba-.png",
  },
  {
    id: "parafuso-7",
    category: 0,
    title: "Parafuso Auto Atarraxante (Cabeça Panela)",
    norm: "DIN 7981 / DIN 7982 / ISO 7049",
    material: "Aço Carbono Cementado / Inox A2",
    grade: "Alta Dureza Superficial",
    application: "União de chapas finas de metal, perfis de alumínio e plásticos.",
    description: "Forma sua própria rosca interna no material no momento da instalação.",
    sizes: ["2.2", "2.9", "3.5", "4.2", "4.8", "5.5", "6.3"],
    image: "/produtos/parafuso_auto_atarraxante_-cabeca_panela-.png",
  },
  {
    id: "parafuso-8",
    category: 0,
    title: "Parafuso Rosca Máquina (Cabeça Panela)",
    norm: "DIN 7985 / DIN 965",
    material: "Aço Carbono / Inox / Latão",
    grade: "Classe 4.8 / 5.8",
    application: "Eletrodomésticos, painéis elétricos e conexões mecânicas com porcas ou furos roscados.",
    description: "Parafusos com cabeça chata ou panela com fendas simples ou Philips.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10"],
    image: "/produtos/parafuso_rosca_maquina_-cabeca_panela-.png",
  },
  {
    id: "parafuso-9",
    category: 0,
    title: "Parafuso Sextavado (Auto Atarraxante Arruelado)",
    norm: "Norma Técnica / ISO 7053",
    material: "Aço Carbono Cementado Zincado",
    grade: "Classe Especial",
    application: "Fixações rápidas de perfis metálicos, calhas e chapas.",
    description: "Combina cabeça sextavada com arruela incorporada e rosca auto-atarraxante.",
    sizes: ["#8", "#10", "#12", "#14"],
    image: "/produtos/parafuso_sextavado_-auto_atarraxante_arruelado-.png",
  },
  {
    id: "parafuso-10",
    category: 0,
    title: "Parafusos para Móveis",
    norm: "Linha moveleira (Cama, Tampo, etc.)",
    material: "Aço Carbono Bicromatizado / Zincado",
    grade: "Leve",
    application: "Montagem de móveis de madeira, MDF e compensados.",
    description: "Modelos como Parafuso Chipboard, Cama e Eixo Moveleiro com rosca especial.",
    sizes: ["3.5 x 16", "4.0 x 40", "4.5 x 50", "5.0 x 60"],
    image: "/produtos/parafusos/image10.jpeg",
  },
  {
    id: "parafuso-11",
    category: 0,
    title: "Parafuso Plastic",
    norm: "Especial para Termoplásticos",
    material: "Aço Carbono Cementado / Temperado",
    grade: "Especial",
    application: "Fixações diretas em carcaças plásticas, brinquedos e eletrônicos.",
    description: "Rosca com ângulo especial que reduz a tensão de expansão no plástico, evitando trincas.",
    sizes: ["2.5", "3.0", "3.5", "4.0", "5.0"],
    image: "/produtos/parafusos/image11.jpeg",
  },
  {
    id: "parafuso-12",
    category: 0,
    title: "Parafuso Drywall",
    norm: "Norma Técnica Drywall",
    material: "Aço Carbono Fosfatizado",
    grade: "Cementado",
    application: "Fixação de placas de gesso acartonado (drywall) em perfis metálicos.",
    description: "Cabeça trombeta e rosca fina/fina ou rosca grossa com ponta agulha.",
    sizes: ["25mm", "35mm", "45mm", "55mm"],
    image: "/produtos/parafusos/image12.jpeg",
  },
  {
    id: "parafuso-13",
    category: 0,
    title: "Parafuso Brocante",
    norm: "DIN 7504",
    material: "Aço Carbono Cementado / Zincado",
    grade: "Alta Resistência",
    application: "Fixação de telhas metálicas, terças e estruturas sem necessidade de pré-furo.",
    description: "Ponta broca que fura, atarraxa e veda/fixa em uma única operação.",
    sizes: ["#10", "#12", "#14"],
    image: "/produtos/parafusos/image13.jpeg",
  },
  {
    id: "parafuso-14",
    category: 0,
    title: "Parafuso para Telha",
    norm: "Norma Técnica",
    material: "Aço Carbono Zincado / Galvanizado",
    grade: "Classe Comercial",
    application: "Fixação de telhas de fibrocimento, alumínio ou zinco em estruturas de madeira ou metal.",
    description: "Com rosca soberba ou rosca máquina acompanhado de arruelas de vedação.",
    sizes: ["5/16\" x 110mm", "5/16\" x 150mm"],
    image: "/produtos/parafusos/image14.jpeg",
  },
  {
    id: "parafuso-15",
    category: 0,
    title: "Parafusos para Andaime",
    norm: "Segurança de Andaimes",
    material: "Aço Carbono de Alta Resistência",
    grade: "Classe 8.8",
    application: "Travamento e fixação de tubos e abraçadeiras em andaimes de obras civil.",
    description: "Parafuso T com porca rápida de alta resistência mecânica.",
    sizes: ["1/2\" x 75mm", "M12 x 80mm"],
    image: "/produtos/parafusos/image15.jpeg",
  },
  {
    id: "parafuso-16",
    category: 0,
    title: "Conjunto para Louça Sanitária",
    norm: "Padrão sanitário",
    material: "Latão / Inox e Buchas Plásticas",
    grade: "Anticorrosivo",
    application: "Instalação e fixação de vasos sanitários e tanques no piso ou parede.",
    description: "Conjunto com parafuso em liga de cobre (latão) ou inox, bucha de nylon e acabamento cromado.",
    sizes: ["Bucha 8", "Bucha 10"],
    image: "/produtos/parafusos/image16.jpeg",
  },
  {
    id: "parafuso-17",
    category: 0,
    title: "Parafuso e Eixo Bicicleta",
    norm: "Linha Duas Rodas",
    material: "Aço Carbono / Liga",
    grade: "Resistente a Impacto",
    application: "Montagem de eixos de rodas, coroas, pedivela e acessórios de bicicletas.",
    description: "Parafusos específicos com roscas finas e tratamentos protetivos contra intempéries.",
    sizes: ["3/8\"", "5/16\"", "M6", "M8"],
    image: "/produtos/parafusos/image17.jpeg",
  },
  {
    id: "parafuso-18",
    category: 0,
    title: "Parafuso Cilíndrico Recartilhado",
    norm: "DIN 653 / DIN 464",
    material: "Aço Carbono / Inox / Latão",
    grade: "Leve",
    application: "Painéis de controle, tampas de proteção e locais que exigem aperto manual constante.",
    description: "Possui cabeça alta recartilhada permitindo aperto e desaperto rápido sem uso de ferramentas.",
    sizes: ["M3", "M4", "M5", "M6", "M8"],
    image: "/produtos/parafusos/image18.jpeg",
  },
  {
    id: "parafuso-19",
    category: 0,
    title: "Parafuso para Arado",
    norm: "ASME B18.9 (Nº 3 Head)",
    material: "Aço Carbono Temperado",
    grade: "Grau 5 / Grau 8",
    application: "Fixação de lâminas de arados, motoniveladoras e implementos agrícolas.",
    description: "Cabeça escareada chata com encaixe quadrado para travamento no furo, oferecendo superfície plana.",
    sizes: ["3/8\"", "1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/parafusos/image19.jpeg",
  },
  {
    id: "parafuso-20",
    category: 0,
    title: "Parafuso para Colheitadeira",
    norm: "Padrão Agrícola",
    material: "Aço Liga Temperado",
    grade: "Classe 8.8 / 10.9",
    application: "Fixação de dedos retráteis, navalhas e componentes internos de colheitadeiras.",
    description: "Projetados para extrema vibração e impacto constante na colheita.",
    sizes: ["M6", "M8", "M10", "M12"],
    image: "/produtos/parafusos/image20.jpeg",
  },
  {
    id: "parafuso-21",
    category: 0,
    title: "Parafuso Sextavado Flangeado Cônico para Silo",
    norm: "Norma Técnica Agro",
    material: "Aço Carbono Galvanizado a Fogo / Geomet",
    grade: "Classe 8.8",
    application: "União de chapas de silos de grãos metálicos e reservatórios de água.",
    description: "Com arruela de vedação de EPDM integrada sob a cabeça para prevenir infiltrações.",
    sizes: ["3/8\" x 1\"", "3/8\" x 1.1/4\"", "M10 x 25mm"],
    image: "/produtos/parafusos/image21.jpeg",
  },
  {
    id: "parafuso-22",
    category: 0,
    title: "Parafuso Correia Elevadora",
    norm: "Norma Elevadoras (Fang Bolt)",
    material: "Aço Carbono Zincado / Inox",
    grade: "Grau 2 / Grau 5",
    application: "Fixação de caçambas em correias transportadoras e elevadores de grãos/minérios.",
    description: "Cabeça chata com garras traseiras que travam na correia e impedem a rotação no aperto.",
    sizes: ["1/4\"", "5/16\"", "3/8\""],
    image: "/produtos/parafusos/image22.jpeg",
  },
  {
    id: "parafuso-23",
    category: 0,
    title: "Parafuso Faca Forrageira",
    norm: "Linha Agrícola",
    material: "Aço Liga de Alta Resistência",
    grade: "Classe 10.9 / 12.9",
    application: "Fixação de facas e cutelos em trituradores, picadores e forrageiras.",
    description: "Parafusos especiais tratados termicamente para resistir a altíssimas forças de cisalhamento.",
    sizes: ["M10", "M12", "M14", "M16"],
    image: "/produtos/parafusos/image23.jpeg",
  },
  {
    id: "parafuso-24",
    category: 0,
    title: "Parafuso Flangeado para Tambor",
    norm: "Norma Recipientes",
    material: "Aço Carbono / Selados",
    grade: "Leve",
    application: "Fechamento de tampas, aros e travas de tambores metálicos e bombonas.",
    description: "Cabeça flangeada de ajuste preciso para lacres de tambores industriais.",
    sizes: ["M8 x 60mm", "M10 x 70mm"],
    image: "/produtos/parafusos/image24.jpeg",
  },
  {
    id: "parafuso-25",
    category: 0,
    title: "Parafuso Terminal Cabo Bateria",
    norm: "Elétrica Automotiva",
    material: "Aço Carbono Revestido / Chumbo / Bronze",
    grade: "Grau Comercial",
    application: "Conexão de cabos elétricos a bornes de baterias automotivas e industriais.",
    description: "Acompanha porca quadrada ou sextavada e revestimento anticorrosão ácida.",
    sizes: ["M6 x 20mm", "5/16\" x 1\""],
    image: "/produtos/parafusos/image25.jpeg",
  },
  {
    id: "parafuso-26",
    category: 0,
    title: "Conjunto Cardan",
    norm: "Linha Automotiva / Agrícola",
    material: "Aço Liga de Alta Resistência",
    grade: "Classe 10.9 / 12.9",
    application: "Fixação de cruzetas e flanges no eixo cardan de veículos e tratores.",
    description: "Parafusos com corpo retificado e porcas de segurança com torque específico.",
    sizes: ["3/8\"", "7/16\"", "1/2\"", "M10", "M12"],
    image: "/produtos/parafusos/image26.jpeg",
  },
  {
    id: "parafuso-27",
    category: 0,
    title: "Parafusos Linha Automotiva",
    norm: "Padrão Montadoras",
    material: "Aço Carbono e Liga Revestidos",
    grade: "Classe 8.8 / 10.9 / 12.9",
    application: "Componentes de motor, suspensão, rodas e fixações críticas em veículos.",
    description: "Parafusos especiais flangeados, cônicos ou prisioneiros sob especificações de montadoras.",
    sizes: ["M8", "M10", "M12", "M14", "M16"],
    image: "/produtos/parafusos/image27.jpeg",
  },
  {
    id: "parafuso-28",
    category: 8,
    title: "Barra Roscada",
    norm: "DIN 975 / DIN 976",
    material: "Aço Carbono, Inox e Latão",
    grade: "Classe 4.8 / 5.6 / 8.8",
    application: "Suspensão de calhas, dutos de ar condicionado, ancoragens e montagens de tubulações.",
    description: "Barras roscadas contínuas de 1 ou 2 metros, cortadas ou adaptadas conforme a necessidade da obra.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\"", "M6", "M8", "M10", "M12", "M16", "M20"],
    image: "/produtos/parafusos/image28.jpeg",
  },
  // Categoria 1: Porcas
  {
    id: "porca-1",
    category: 1,
    title: "Porca Sextavada",
    norm: "DIN 934 / ISO 4032",
    material: "Aço Carbono / Inox / Latão",
    grade: "Classe 5 / 8 / 10 / Inox A2",
    application: "Fixação e união em conjunto com parafusos sextavados e barras roscadas.",
    description: "Porca sextavada padrão de rosca métrica e em polegadas para fixação geral.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10", "M12", "M16", "M20", "M24", "1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/porca_sextavada.png",
  },
  {
    id: "porca-2",
    category: 1,
    title: "Porca Sextavada Baixa",
    norm: "DIN 439 / ISO 4035",
    material: "Aço Carbono / Inox",
    grade: "Classe 04 / 05",
    application: "Contra-porca de travamento ou locais com espaço de montagem extremamente limitado.",
    description: "Perfil de altura reduzida projetado para atuar como contra-porca ou sob restrição de espaço.",
    sizes: ["M6", "M8", "M10", "M12", "M16", "M20", "1/4\"", "3/8\"", "1/2\""],
    image: "/produtos/porca_sextavada_baixa.png",
  },
  {
    id: "porca-3",
    category: 1,
    title: "Porca Sextavada ASTM A194 2H",
    norm: "ASTM A194 Grau 2H / ASME B18.2.2",
    material: "Aço Carbono Temperado e Revenido",
    grade: "Grau 2H (Alta Resistência)",
    application: "Vasos de pressão, flanges de tubulação, caldeiras e conexões de alta temperatura/pressão.",
    description: "Porca sextavada pesada de alta resistência mecânica indicada para aplicações de alta temperatura e alta pressão.",
    sizes: ["1/2\"", "5/8\"", "3/4\"", "7/8\"", "1\"", "1.1/8\"", "1.1/4\"", "1.1/2\""],
    image: "/produtos/porca_sextavada_astm_a194_2h.png",
  },
  {
    id: "porca-4",
    category: 1,
    title: "Porca Sextavada ASTM A563",
    norm: "ASTM A563 Grau A / B / DH",
    material: "Aço Carbono",
    grade: "Grau A / DH",
    application: "Montagens estruturais em conjunto com parafusos ASTM A325 e conexões de aço carbono.",
    description: "Porcas estruturais destinadas a juntas flangeadas e elementos estruturais sob alta tração.",
    sizes: ["1/2\"", "5/8\"", "3/4\"", "7/8\"", "1\"", "1.1/4\""],
    image: "/produtos/porca_sextavada_astm_a563.png",
  },
  {
    id: "porca-5",
    category: 1,
    title: "Porca Sextavada Flangeada",
    norm: "DIN 6923 / EN 1661",
    material: "Aço Carbono / Inox",
    grade: "Classe 8 / 10",
    application: "Linha de montagem industrial e automotiva.",
    description: "Possui flange lisa integrada na base que atua como arruela e distribui a força de fixação.",
    sizes: ["M5", "M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/porca_sextavada_flangeada.png",
  },
  {
    id: "porca-6",
    category: 1,
    title: "Porca Sextavada (Flangeada Serrilhada)",
    norm: "DIN 6923 Serrilhada",
    material: "Aço Carbono Zincado",
    grade: "Classe 8",
    application: "Sistemas elétricos, aterramento e locais expostos a micro-vibrações mecânicas.",
    description: "Apresenta serrilhas auto-travantes sob a flange para fixação firme que previne o afrouxamento.",
    sizes: ["M5", "M6", "M8", "M10", "M12"],
    image: "/produtos/porca_sextavada_-flangeada_serrilhada-.png",
  },
  {
    id: "porca-7",
    category: 1,
    title: "Porca Sextavada Torque",
    norm: "IFI-100 / Prevailing Torque Type",
    material: "Aço Liga de Alta Resistência",
    grade: "Grau C / Classe 10",
    application: "Indústria automotiva, suspensão, pontes e juntas de alta vibração contínua.",
    description: "Porca auto-travante totalmente metálica por deformação mecânica controlada da rosca superior.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\"", "M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/porca_sextavada_torque.png",
  },
  {
    id: "porca-8",
    category: 1,
    title: "Porca Flangeada com Nylon",
    norm: "Norma Técnica / DIN 6926",
    material: "Aço Carbono / Inserto de Nylon",
    grade: "Classe 8 / 10",
    application: "Montagens industriais e de equipamentos sujeitos a vibração extrema sem arruelas avulsas.",
    description: "Combina as vantagens da flange de assentamento com o travamento eficiente do inserto de nylon.",
    sizes: ["M6", "M8", "M10", "M12"],
    image: "/produtos/porca_flangeada_com_nylon.png",
  },
  {
    id: "porca-9",
    category: 1,
    title: "Porca Travante Alta com Nylon",
    norm: "DIN 982 / ISO 7040",
    material: "Aço Carbono / Nylon",
    grade: "Classe 8 / 10",
    application: "Máquinas industriais e veículos agrícolas sujeitos a solavancos.",
    description: "Perfil alto com anel interno de nylon para evitar desenroscamento acidental.",
    sizes: ["M5", "M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/porca_travante_alta_com_nylon.png",
  },
  {
    id: "porca-10",
    category: 1,
    title: "Porca Travante Baixa com Nylon",
    norm: "DIN 985 / ISO 10511",
    material: "Aço Carbono / Nylon",
    grade: "Classe 8 / 10",
    application: "Aplicações com restrição de altura mantendo segurança contra vibração.",
    description: "Perfil reduzido mantendo o anel auto-travante de nylon no topo.",
    sizes: ["M4", "M5", "M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/porca_travante_baixa_com_nylon.png",
  },
  {
    id: "porca-11",
    category: 1,
    title: "Porca Quadrada",
    norm: "DIN 557",
    material: "Aço Carbono / Inox",
    grade: "Classe 5",
    application: "Canaletas de aluminio, perfilados e montagens de madeira.",
    description: "Superfície de apoio ampliada de quatro lados indicada para encaixe em canaletas.",
    sizes: ["M5", "M6", "M8", "M10"],
    image: "/produtos/porca_quadrada.png",
  },
  {
    id: "porca-12",
    category: 1,
    title: "Porca Borboleta",
    norm: "DIN 315",
    material: "Aço Carbono Zincado / Inox / Latão",
    grade: "Leve",
    application: "Ajustes rápidos manuais frequentes, tampas de caixas de inspeção, suportes de bateria e pedestais.",
    description: "Abas laterais (orelhas) que permitem o aperto e desaperto direto com os dedos, sem chaves de aperto.",
    sizes: ["M4", "M5", "M6", "M8", "M10", "M12", "1/4\"", "5/16\"", "3/8\"", "1/2\""],
    image: "/produtos/porcas/image11.jpeg",
  },
  {
    id: "porca-13",
    category: 1,
    title: "Porca Dupla",
    norm: "Padrão de Acoplamento",
    material: "Aço Carbono Zincado / Inox",
    grade: "Classe 8",
    application: "Acoplamento e extensão de tirantes roscados e barras roscadas contínuas.",
    description: "Corpo alongado com comprimento equivalente a três vezes o diâmetro nominal da rosca.",
    sizes: ["1/4\" x 3/4\"", "3/8\" x 1.1/8\"", "1/2\" x 1.1/2\"", "M6 x 18", "M8 x 24", "M10 x 30", "M12 x 36"],
    image: "/produtos/porcas/image12.jpeg",
  },
  {
    id: "porca-14",
    category: 1,
    title: "Porca Castelo sem Coroa",
    norm: "DIN 937 / DIN 935 Tipo B",
    material: "Aço Carbono / Inox",
    grade: "Classe 8 / 10",
    application: "Eixos rotativos, cubos de roda e suspensões sujeitos a forças de rotação e vibração severas.",
    description: "Possui ranhuras para travamento mecânico do parafuso prisioneiro ou eixo através de cupilha (contra-pino).",
    sizes: ["M10", "M12", "M16", "M20", "M24", "M30"],
    image: "/produtos/porcas/image13.jpeg",
  },
  {
    id: "porca-15",
    category: 1,
    title: "Porca Castelo com Coroa Alta",
    norm: "DIN 935 / ISO 7035",
    material: "Aço Carbono e Liga / Inox",
    grade: "Classe 8 / 10 / 12",
    application: "Montagens críticas de segurança industrial pesada, eixos ferroviários e implementos agrícolas.",
    description: "Apresenta uma coroa cilíndrica ranhurada alta sobreposta ao corpo sextavado para travamento com cupilha.",
    sizes: ["M12", "M16", "M20", "M24", "M30", "M36"],
    image: "/produtos/porcas/image14.jpeg",
  },
  {
    id: "porca-16",
    category: 1,
    title: "Porca Castelo com Coroa Baixa",
    norm: "DIN 937 Baixa",
    material: "Aço Carbono / Zincado",
    grade: "Classe 04 / 05",
    application: "Eixos traseiros de veículos e fixações rotativas compactas.",
    description: "Perfil baixo com ranhuras de castelo sobrepostas para uso com cupilhas em eixos curtos.",
    sizes: ["M10", "M12", "M16", "M20", "M24"],
    image: "/produtos/porcas/image15.jpeg",
  },
  {
    id: "porca-17",
    category: 1,
    title: "Porca Sextavada de Solda",
    norm: "DIN 929",
    material: "Aço Baixo Carbono (Soldável)",
    grade: "Classe 4 / 5 (Compatível com solda)",
    application: "Fixação permanente em chapas metálicas por solda a ponto na indústria automobilística e de eletrodomésticos.",
    description: "Possui projeções de solda (guias) na base para facilitar o posicionamento e fusão perfeita na chapa.",
    sizes: ["M4", "M5", "M6", "M8", "M10", "M12"],
    image: "/produtos/porcas/image16.jpeg",
  },
  {
    id: "porca-18",
    category: 1,
    title: "Porca Quadrada de Solda",
    norm: "DIN 928",
    material: "Aço Soldável",
    grade: "Classe Especial de Solda",
    application: "Gabinete de equipamentos industriais, rack de servidores e chapas estruturais de aço.",
    description: "Quatro projeções de soldagem nos cantos inferiores garantem fixação por solda de ponto.",
    sizes: ["M5", "M6", "M8", "M10", "M12"],
    image: "/produtos/porcas/image17.jpeg",
  },
  {
    id: "porca-19",
    category: 1,
    title: "Porca Calota",
    norm: "DIN 1587",
    material: "Aço Carbono Zincado / Latão / Inox",
    grade: "Classe 6 / 8",
    application: "Proteção de pontas de rosca, acabamento estético em brinquedos, móveis e corrimãos.",
    description: "Porca sextavada com cúpula esférica (calota) fechada para proteção contra ferimentos e oxidação.",
    sizes: ["M4", "M5", "M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/porcas/image18.jpeg",
  },
  {
    id: "porca-20",
    category: 1,
    title: "Porca Calota Forma Baixa",
    norm: "DIN 917",
    material: "Aço Carbono / Inox",
    grade: "Classe 6 / 8",
    application: "Proteção de rosca sob limites estreitos de projeto estético ou espaço.",
    description: "Modelo baixo fechado de calota arredondada para segurança de cantos vivos roscados.",
    sizes: ["M5", "M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/porcas/image19.jpeg",
  },
  {
    id: "porca-21",
    category: 1,
    title: "Porca Fendada",
    norm: "DIN 546",
    material: "Latão / Inox / Aço Carbono",
    grade: "Leve",
    application: "Montagens de painéis de instrumentos elétricos, aparelhos ópticos e mecânica fina.",
    description: "Porca redonda cilíndrica com uma fenda centralizada para aperto simples com chave de fenda.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10"],
    image: "/produtos/porcas/image20.jpeg",
  },
  {
    id: "porca-22",
    category: 1,
    title: "Porca Sextavada de Roda",
    norm: "Especificação Automotiva",
    material: "Aço Liga Temperado e Cromado",
    grade: "Classe 10.9",
    application: "Fixação de rodas de automóveis de passeio, picapes, vans e caminhões.",
    description: "Possui assentamento cônico ou esférico e acabamento cromado de alta durabilidade mecânica.",
    sizes: ["M12 x 1.25", "M12 x 1.50", "M14 x 1.50", "1/2\" UNF"],
    image: "/produtos/porcas/image21.jpeg",
  },
  {
    id: "porca-23",
    category: 1,
    title: "Porca Garra",
    norm: "Moveleira (T-Nut)",
    material: "Aço Carbono Zincado",
    grade: "Leve",
    application: "Fixação de rodízios, pés niveladores e painéis em chapas de madeira (MDF/Compensado).",
    description: "Possui quatro garras traseiras que cravam na madeira durante o aperto, impedindo o giro.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "M6", "M8", "M10"],
    image: "/produtos/porcas/image22.jpeg",
  },
  {
    id: "porca-24",
    category: 1,
    title: "Porca Pall Nut de Segurança",
    norm: "DIN 7967 / Counter Nut",
    material: "Aço Carbono Mola",
    grade: "Mola Temperada",
    application: "Travamento de porcas sextavadas padrão em redes de transmissão elétrica e torres de telefonia.",
    description: "Porca chapa leve estampara com perfil elástico de travamento de rosca contra vibração severa.",
    sizes: ["M8", "M10", "M12", "M16", "M20", "M24"],
    image: "/produtos/porcas/image23.jpeg",
  },
  {
    id: "porca-25",
    category: 1,
    title: "Prolongador",
    norm: "Norma Interna",
    material: "Aço Carbono Zincado",
    grade: "Grau 5",
    application: "Distanciamento de chapas, painéis elétricos, fixação suspensa e ajustes de nivelamento.",
    description: "Porca sextavada cilíndrica estendida para emendar barras ou servir de espaçador roscado.",
    sizes: ["1/4\"", "3/8\"", "1/2\"", "M6", "M8", "M10", "M12"],
    image: "/produtos/porcas/image24.jpeg",
  },
  {
    id: "porca-26",
    category: 1,
    title: "Porca U",
    norm: "Tipo Spire / Chimney Nut",
    material: "Aço Mola Zincado",
    grade: "Mola temperada",
    application: "Fixação de molduras plásticas, painéis internos de automóveis e chapas de metal finas.",
    description: "Clipe metálico em formato U com rosca integrada projetado para deslizar sobre a borda de painéis.",
    sizes: ["#8", "#10", "M5", "M6"],
    image: "/produtos/porcas/image25.jpeg",
  },
  // Categoria 2: Arruelas
  {
    id: "arruela-1",
    category: 2,
    title: "Arruela Lisa",
    norm: "DIN 125 / ISO 7089",
    material: "Aço Carbono / Inox / Latão",
    grade: "100HV / 200HV",
    application: "Distribuição da força de aperto, proteção da chapa contra riscos e deformações.",
    description: "Arruela plana padrão que distribui a carga da cabeça do parafuso ou porca uniformemente.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10", "M12", "M16", "M20", "M24", "3/16\"", "1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/arruela/image1.jpeg",
  },
  {
    id: "arruela-2",
    category: 2,
    title: "Arruela Lisa com Furo Quadrado",
    norm: "Norma Interna / Moveleira",
    material: "Aço Carbono Zincado",
    grade: "Leve",
    application: "Uso conjunto com parafusos franceses em estruturas de madeira.",
    description: "Furo quadrado central projetado para encaixe perfeito do pescoço quadrado do parafuso francês.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\"", "M6", "M8", "M10", "M12"],
    image: "/produtos/arruela/image2.jpeg",
  },
  {
    id: "arruela-3",
    category: 2,
    title: "Arruela Aba Larga",
    norm: "DIN 9021 / ISO 7093",
    material: "Aço Carbono / Inox",
    grade: "100HV",
    application: "Estruturas de madeira, chapas plásticas ou materiais macios que necessitam de grande área de apoio.",
    description: "Possui diâmetro externo aproximadamente três vezes maior que o diâmetro nominal da rosca.",
    sizes: ["M4", "M5", "M6", "M8", "M10", "M12", "M16", "1/4\"", "5/16\"", "3/8\"", "1/2\""],
    image: "/produtos/arruela/image3.jpeg",
  },
  {
    id: "arruela-4",
    category: 2,
    title: "Arruela de Funileiro",
    norm: "Especificação de Funilaria",
    material: "Aço Carbono Zincado",
    grade: "Comercial",
    application: "Fixação de calhas, rufos, dutos de ar, chapas de zinco e trabalhos de funilaria em geral.",
    description: "Diâmetro externo ampliado e espessura fina para vedação e fixação de chapas de bitola fina.",
    sizes: ["3/16\" x 1\"", "1/4\" x 1\"", "1/4\" x 1.1/4\"", "5/16\" x 1.1/4\""],
    image: "/produtos/arruela/image4.jpeg",
  },
  {
    id: "arruela-5",
    category: 2,
    title: "Arruela Narrow",
    norm: "DIN 433 / ISO 7092",
    material: "Aço Carbono / Inox",
    grade: "140HV",
    application: "Uso em conjunto com parafusos Allen cabeça cilíndrica onde o espaço de alojamento é limitado.",
    description: "Possui diâmetro externo reduzido para se alojar perfeitamente em rebaixos estreitos de máquinas.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/arruela/image5.jpeg",
  },
  {
    id: "arruela-6",
    category: 2,
    title: "Arruela de Pressão",
    norm: "DIN 127 B / ASME B18.21.1",
    material: "Aço Mola / Inox",
    grade: "Mola Temperada",
    application: "Equipamentos com vibração constante, motores, bombas e juntas automotivas.",
    description: "Arruela helicoidal que cria tensão mecânica constante para travar o parafuso contra folgas.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10", "M12", "M16", "M20", "3/16\"", "1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/arruela/image6.jpeg",
  },
  {
    id: "arruela-7",
    category: 2,
    title: "Arruela de Pressão Dupla",
    norm: "Norma Especial de Tração",
    material: "Aço Mola Carbono",
    grade: "Alta Resistência",
    application: "Conexões pesadas ferroviárias e montagem de torres de transmissão.",
    description: "Estrutura helicoidal dupla que fornece força de mola superior e maior amplitude de travamento.",
    sizes: ["M12", "M16", "M20", "M24", "1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/arruela/image7.jpeg",
  },
  {
    id: "arruela-8",
    category: 2,
    title: "Arruela de Pressão Cônica para Parafuso de Roda",
    norm: "Padrão Automotivo",
    material: "Aço Mola Temperado",
    grade: "Classe Alta",
    application: "Instalação de prisioneiros e parafusos em rodas de caminhões e ônibus.",
    description: "Formato cônico elástico projetado para absorver choques mecânicos e manter o torque de aperto da roda.",
    sizes: ["M18", "M20", "M22", "7/8\""],
    image: "/produtos/arruela/image8.jpeg",
  },
  {
    id: "arruela-9",
    category: 2,
    title: "Arruela de Vedação",
    norm: "Norma Vedação",
    material: "Aço Galvanizado com Borracha EPDM",
    grade: "Industrial / Estanque",
    application: "Fixação de telhas metálicas, galpões e estruturas externas expostas à chuva.",
    description: "Arruela metálica acoplada a um inserto de borracha vulcanizada (EPDM) para vedação absoluta contra infiltração.",
    sizes: ["#10 (4.8mm)", "#12 (5.5mm)", "#14 (6.3mm)", "5/16\""],
    image: "/produtos/arruela/image9.jpeg",
  },
  {
    id: "arruela-10",
    category: 2,
    title: "Arruela de Vedação Cônica",
    norm: "Vedação Cônica",
    material: "Alumínio / Cobre / EPDM",
    grade: "Maleável",
    application: "Bujões de cárter, conexões hidráulicas de alta pressão e compressores.",
    description: "Formato cônico que se deforma de maneira controlada sob aperto para preencher micro-frestas e vedar fluidos.",
    sizes: ["M10", "M12", "M14", "M16", "M20", "1/4\"", "3/8\"", "1/2\""],
    image: "/produtos/arruela/image10.jpeg",
  },
  {
    id: "arruela-11",
    category: 2,
    title: "Arruela Dentada",
    norm: "DIN 6797 Forma J (Dentado Interno)",
    material: "Aço Carbono / Inox",
    grade: "Mola Temperada",
    application: "Equipamentos eletroeletrônicos, conexões de painéis elétricos para evitar vibração e garantir contato elétrico.",
    description: "Dentes voltados para a parte interna que cravam na superfície e na cabeça do fixador.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10", "M12"],
    image: "/produtos/arruela/image11.jpeg",
  },
  {
    id: "arruela-12",
    category: 2,
    title: "Arruela Dentada Externa",
    norm: "DIN 6797 Forma A (Dentado Externo)",
    material: "Aço Carbono / Inox",
    grade: "Mola Temperada",
    application: "Juntas de estruturas elétricas de aterramento, montagens de eletrodomésticos e componentes de motores.",
    description: "Dentes externos em ângulo que travam mecanicamente sob aperto, impedindo giros indesejados.",
    sizes: ["M4", "M5", "M6", "M8", "M10", "M12"],
    image: "/produtos/arruela/image12.jpeg",
  },
  {
    id: "arruela-13",
    category: 2,
    title: "Arruela Quadrada Cunha",
    norm: "DIN 434 / DIN 435",
    material: "Aço Carbono Galvanizado a Fogo",
    grade: "Grau Estrutural",
    application: "Ajuste de inclinação e nivelamento em vigas I e U de estruturas metálicas.",
    description: "Formato quadrado cuneiforme (com inclinação de 8% ou 14%) para compensar a inclinação de perfis laminados.",
    sizes: ["M12", "M16", "M20", "M24", "1/2\"", "5/8\"", "3/4\"", "7/8\""],
    image: "/produtos/arruela/image13.jpeg",
  },
  {
    id: "arruela-14",
    category: 2,
    title: "Anilha",
    norm: "Norma Comercial",
    material: "Plástico Nylon / Fibra Vermelha",
    grade: "Isolante",
    application: "Isolamento elétrico de componentes, vedações leves de água e conexões de tubos de instrumentação.",
    description: "Anel isolante macio de nylon ou fibra para absorção e isolação galvânica.",
    sizes: ["M3", "M4", "M5", "M6", "M8", "M10"],
    image: "/produtos/arruela/image14.jpeg",
  },
  {
    id: "arruela-15",
    category: 2,
    title: "Mola Prato",
    norm: "DIN 2093",
    material: "Aço Mola de Alta Performance",
    grade: "Temperado Especial",
    application: "Flanges de tubulações sob ciclos térmicos de expansão, freios industriais e prensas.",
    description: "Arruela cônica que atua como mola de alta capacidade de carga em espaços axiais extremamente compactos.",
    sizes: ["M8", "M10", "M12", "M16", "M20", "M24", "M30"],
    image: "/produtos/arruela/image1.jpeg",
  },
  // Categoria 3: Chumbadores Mecânicos
  {
    id: "chumbador-1",
    category: 3,
    title: "Cone e Jaqueta",
    norm: "Especificação de Expansão",
    material: "Aço Carbono Zincado",
    grade: "Grau Industrial",
    application: "Fixação de portões, grades, corrimãos e estruturas metálicas leves em concreto.",
    description: "Conjunto clássico de expansão mecânica por torque contendo jaqueta de chapa e cone interno.",
    sizes: ["1/4\" x 2\"", "5/16\" x 2.1/4\"", "3/8\" x 3\"", "1/2\" x 4\""],
    image: "/produtos/chumbadores mecanicos/image1.jpeg",
  },
  {
    id: "chumbador-2",
    category: 3,
    title: "Prolongador",
    norm: "Norma Técnica",
    material: "Aço Carbono Zincado",
    grade: "Grau 5",
    application: "Ajustes de profundidade e ancoragens em furos profundos de concreto.",
    description: "Elemento prolongador para corpo de chumbadores mecânicos de expansão.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\""],
    image: "/produtos/chumbadores mecanicos/image2.jpeg",
  },
  {
    id: "chumbador-3",
    category: 3,
    title: "Chumbador CB com Parafuso",
    norm: "Especificação Técnica CB",
    material: "Aço Carbono / Zincado",
    grade: "Alta Resistência",
    application: "Fixação de máquinas, equipamentos industriais pesados e pilares metálicos em bases de concreto.",
    description: "Chumbador de expansão controlada por torque fornecido completo com parafuso sextavado.",
    sizes: ["1/4\" x 2\"", "5/16\" x 3\"", "3/8\" x 3.3/4\"", "1/2\" x 4.1/4\"", "5/8\" x 5\""],
    image: "/produtos/chumbadores mecanicos/image3.jpeg",
  },
  {
    id: "chumbador-4",
    category: 3,
    title: "Chumbador CB com Prisioneiro",
    norm: "Norma CB / Prisioneiro",
    material: "Aço Carbono Zincado",
    grade: "Alta Resistência",
    application: "Instalações suspensas, fixações onde a peça a ser montada é encaixada por cima do prisioneiro.",
    description: "Chumbador de jaqueta e cone fornecido com prisioneiro roscado, arruela lisa e porca sextavada.",
    sizes: ["1/4\" x 3\"", "5/16\" x 3.1/4\"", "3/8\" x 4\"", "1/2\" x 4.3/4\"", "5/8\" x 5.1/2\""],
    image: "/produtos/chumbadores mecanicos/image4.jpeg",
  },
  {
    id: "chumbador-5",
    category: 3,
    title: "Chumbador PB Parabolt",
    norm: "ASME B18.2.1 / Ancoragem",
    material: "Aço Carbono Zincado / Inox A2",
    grade: "Grau Estrutural",
    application: "Instalação de colunas estruturais, pontes rolantes, vigas metálicas secundárias e fixações pesadas de segurança.",
    description: "Chumbador de expansão do tipo cunha de alto desempenho e excelente capacidade de carga.",
    sizes: ["1/4\" x 2\"", "3/8\" x 3\"", "1/2\" x 4\"", "5/8\" x 5\"", "3/4\" x 6\"", "3/4\" x 8\""],
    image: "/produtos/chumbadores mecanicos/image5.jpeg",
  },
  {
    id: "chumbador-6",
    category: 3,
    title: "Chumbador AF Alfa",
    norm: "Norma Alfa",
    material: "Aço Carbono Zincado",
    grade: "Industrial",
    application: "Ancoragens rápidas de média capacidade, fixação de trilhos e bases de máquinas leves.",
    description: "Chumbador de expansão mecânica com camisa de chapa fechada de montagem passante.",
    sizes: ["M8 x 65mm", "M10 x 80mm", "M12 x 100mm"],
    image: "/produtos/chumbadores mecanicos/image6.jpeg",
  },
  {
    id: "chumbador-7",
    category: 3,
    title: "Chumbador OM Ômega",
    norm: "Norma Ômega de Expansão",
    material: "Aço Carbono / Inox",
    grade: "Grau Estrutural",
    application: "Instalação de bandejas de cabos, dutos, suspensões e tubulações industriais.",
    description: "Ancoragem de alto desempenho com jaqueta bi-partida de geometria especial.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\""],
    image: "/produtos/chumbadores mecanicos/image7.jpeg",
  },
  {
    id: "chumbador-8",
    category: 3,
    title: "Chumbador CB Pitão",
    norm: "Especificação CB Argola",
    material: "Aço Carbono / Pitão de Aço",
    grade: "Comercial",
    application: "Ancoragem de cabos de sustentação, redes de proteção e fixação de correntes em concreto.",
    description: "Chumbador expansivo de camisa e cone acoplado a um pitão (gancho fechado / argola).",
    sizes: ["1/4\" x 2\"", "5/16\" x 2.1/4\"", "3/8\" x 3\"", "1/2\" x 4\""],
    image: "/produtos/chumbadores mecanicos/image8.jpeg",
  },
  {
    id: "chumbador-9",
    category: 3,
    title: "Chumbador RS",
    norm: "Norma RS de Ancoragem",
    material: "Aço Carbono Zincado",
    grade: "Grau Industrial",
    application: "Ancoragens em alvenarias estruturais e concretos de média resistência.",
    description: "Chumbador com bucha de nylon de alta qualidade e parafuso rosca soberba sextavado.",
    sizes: ["Bucha 8", "Bucha 10", "Bucha 12"],
    image: "/produtos/chumbadores mecanicos/image9.jpeg",
  },
  {
    id: "chumbador-10",
    category: 3,
    title: "Chumbador UR",
    norm: "Especificação UR",
    material: "Aço Carbono Zincado",
    grade: "Médio",
    application: "Instalação de forros suspensos, tirantes e suportes de climatização.",
    description: "Chumbador leve de batedor mecânico com expansão por deformação interna.",
    sizes: ["1/4\"", "5/16\"", "3/8\""],
    image: "/produtos/chumbadores mecanicos/image10.jpeg",
  },
  {
    id: "chumbador-11",
    category: 3,
    title: "Chumbador RX",
    norm: "Norma RX de Ancoragem",
    material: "Aço Carbono / Camisa Especial",
    grade: "Alta Performance",
    application: "Instalações onde o diâmetro do furo é idêntico ao diâmetro do parafuso, agilizando a instalação.",
    description: "Chumbador mecânico de expansão por torque ideal para furos passantes na peça a ser fixada.",
    sizes: ["M6", "M8", "M10", "M12", "M16"],
    image: "/produtos/chumbadores mecanicos/image11.jpeg",
  },
  {
    id: "chumbador-12",
    category: 3,
    title: "Chumbador RXS",
    norm: "Especificação RXS",
    material: "Aço Carbono / Tratado",
    grade: "Alta Resistência",
    application: "Aplicações de segurança onde o chumbador deve ficar rente ou embutido na superfície do concreto.",
    description: "Chumbador do tipo luva expansiva de camisa robusta com parafuso sextavado plano de precisão.",
    sizes: ["M8", "M10", "M12"],
    image: "/produtos/chumbadores mecanicos/image12.jpeg",
  },
  {
    id: "chumbador-13",
    category: 3,
    title: "Chumbador PBI",
    norm: "Especificação PBI",
    material: "Aço Carbono / Inserção",
    grade: "Industrial",
    application: "Ancoragens internas de rosca fêmea no concreto para receber parafusos de maquinários ou prisioneiros.",
    description: "Chumbador de rosca interna de expansão controlada por deformador batedor.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\""],
    image: "/produtos/chumbadores mecanicos/image13.jpeg",
  },
  {
    id: "chumbador-14",
    category: 3,
    title: "Parafuso PCE para Concreto",
    norm: "Parafuso de Concreto Técnico",
    material: "Aço Liga Cementado com Geomet / Zincado",
    grade: "Classe 10.9 / Alta dureza na ponta",
    application: "Instalação ultra-rápida de trilhos, suportes pesados, barreiras físicas e maquinários diretamente no concreto.",
    description: "Parafuso especial que corta a sua própria rosca diretamente no furo prévio do concreto, sem buchas.",
    sizes: ["6mm x 50mm", "8mm x 70mm", "10mm x 100mm", "12mm x 120mm"],
    image: "/produtos/chumbadores mecanicos/image14.jpeg",
  },
  {
    id: "chumbador-15",
    category: 3,
    title: "Parafuso PCA para Concreto",
    norm: "Parafuso Concreto Leve",
    material: "Aço Carbono Cementado",
    grade: "Alta Dureza",
    application: "Fixações rápidas em concreto, tijolos maciços e alvenaria.",
    description: "Parafuso ancorador direto com cabeça flangeada serrilhada para aperto firme.",
    sizes: ["6.3mm x 50mm", "6.3mm x 75mm", "7.5mm x 100mm"],
    image: "/produtos/chumbadores mecanicos/image15.jpeg",
  },
  {
    id: "chumbador-16",
    category: 3,
    title: "Batedor BT",
    norm: "Acessório de Instalação",
    material: "Aço Carbono de Impacto",
    grade: "Ferramenta Temperada",
    application: "Instalação por percussão de chumbadores do tipo batedor ou deformação interna (ex: PBI / UR).",
    description: "Pino batedor guia para garantir a expansão segura e uniforme de chumbadores sem danificar a rosca.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\""],
    image: "/produtos/chumbadores mecanicos/image16.png",
  },
  {
    id: "chumbador-17",
    category: 3,
    title: "Batedor BTE",
    norm: "Acessório Especial",
    material: "Aço Liga de Impacto",
    grade: "Ferramenta Temperada",
    application: "Instalação técnica de chumbadores tipo expansão interna em furos suspensos.",
    description: "Pino batedor com empunhadura ergonômica de proteção contra batidas no instalador.",
    sizes: ["3/8\"", "1/2\""],
    image: "/produtos/chumbadores mecanicos/image17.png",
  },
  {
    id: "chumbador-18",
    category: 3,
    title: "Batedor BTP",
    norm: "Padrão Industrial BT",
    material: "Aço Carbono Resistente",
    grade: "Impacto Pesado",
    application: "Uso profissional na instalação de chumbadores industriais de deformação mecânica rápida.",
    description: "Ferramenta batedora calibrada para expansão sob marretadas contínuas.",
    sizes: ["1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/chumbadores mecanicos/image18.png",
  },
  // Categoria 4: Chumbadores Químicos
  {
    id: "quimico-1",
    category: 8,
    title: "Barra Roscada",
    norm: "DIN 976 / ASTM F1554",
    material: "Aço Carbono / Inox",
    grade: "Classe 5.8 / 8.8 / Inox A4",
    application: "Ancoragem química de pilares, vigas, consoles e fixações pesadas de segurança em concreto.",
    description: "Barra roscada chanfrada com ponta cortante e sextavado de acoplamento de instalação química.",
    sizes: ["M8", "M10", "M12", "M16", "M20", "M24", "1/2\"", "5/8\"", "3/4\"", "7/8\"", "1\""],
    image: "/produtos/chumbadores quimicos/image1.jpeg",
  },
  {
    id: "quimico-2",
    category: 4,
    title: "Ampola QA para Barra Roscada",
    norm: "ETA Ancoragem Química",
    material: "Resina Vinilester e Areia Quartzosa",
    grade: "Alta Carga",
    application: "Fixações rápidas de barras roscadas prontas em concreto maciço.",
    description: "Ampola de vidro calibrada contendo resina vinilester e catalisador ensacado separadamente.",
    sizes: ["M8", "M10", "M12", "M16", "M20", "M24"],
    image: "/produtos/chumbadores quimicos/image2.jpeg",
  },
  {
    id: "quimico-3",
    category: 4,
    title: "Ampola QV para Vergalhão",
    norm: "ETA / Ancoragem Vergalhão",
    material: "Resina Epóxi-Acrilato",
    grade: "Segurança Elevada",
    application: "Ligação técnica de barras de reforço (vergalhões/arranques) de estruturas de concreto.",
    description: "Ampola química de vidro desenvolvida para adesão e ancoragem perfeita de vergalhões de construção civil.",
    sizes: ["#8mm", "#10mm", "#12mm", "#16mm", "#20mm", "#25mm"],
    image: "/produtos/chumbadores quimicos/image3.jpeg",
  },
  {
    id: "quimico-4",
    category: 4,
    title: "Injeção Epoxi",
    norm: "ETA Opção 1 (Concreto Fissurado)",
    material: "Resina Epóxi Pura 3:1",
    grade: "Máximo Desempenho / Cargas Sísmicas",
    application: "Ancoragem de barras de reforço de grande diâmetro, furos profundos e furos diamantados úmidos.",
    description: "Adesivo estrutural por injeção de epóxi puro de cura lenta e altíssima força de adesão.",
    sizes: ["Cartucho 390ml", "Cartucho 585ml"],
    image: "/produtos/chumbadores quimicos/image4.jpeg",
  },
  {
    id: "quimico-5",
    category: 4,
    title: "Injeção Metacrilato",
    norm: "ETA Homologação Química",
    material: "Resina Metacrilato sem Estireno",
    grade: "Cura Rápida / Média-Alta Carga",
    application: "Ancoragem química de alto rendimento em concreto, alvenaria de bloco oco e tijolos maciços.",
    description: "Adesivo de injeção bi-componente de cura extra rápida ideal para climas frios e instalações ágeis.",
    sizes: ["Cartucho 300ml", "Cartucho 410ml"],
    image: "/produtos/chumbadores quimicos/image5.jpeg",
  },
  {
    id: "quimico-6",
    category: 4,
    title: "Injeção Poliester",
    norm: "Especificação Química Leve",
    material: "Resina Poliéster Bi-componente",
    grade: "Carga Média / Uso Geral",
    application: "Fixação de suportes de TV, ar condicionado, portões e grades em alvenaria e concreto leve.",
    description: "Resina de injeção econômica ideal para fixações cotidianas e excelente custo-benefício.",
    sizes: ["Cartucho 300ml"],
    image: "/produtos/chumbadores quimicos/image6.jpeg",
  },
  {
    id: "quimico-7",
    category: 4,
    title: "Camisa",
    norm: "Acessório para Oco",
    material: "Plástico Polipropileno / Camisa Metálica",
    grade: "Acessório",
    application: "Instalação de ancoragem química por injeção em blocos ocos e tijolos vazados.",
    description: "Bucha perfurada (camisa) que retém a resina injetada, permitindo a expansão controlada na cavidade.",
    sizes: ["12x80mm", "15x85mm", "16x85mm", "20x85mm"],
    image: "/produtos/chumbadores quimicos/image7.jpeg",
  },
  {
    id: "quimico-8",
    category: 4,
    title: "Bicos",
    norm: "Misturador Estático",
    material: "Plástico Técnico",
    grade: "Descartável",
    application: "Mistura perfeita dos dois componentes da resina de injeção no bocal de saída do cartucho.",
    description: "Bico misturador estático com espirais internas helicoidais de alta homogeneização.",
    sizes: ["Padrão para cartuchos 300ml/410ml"],
    image: "/produtos/chumbadores quimicos/image8.jpeg",
  },
  {
    id: "quimico-9",
    category: 4,
    title: "Aplicadores",
    norm: "Ferramenta de Injeção",
    material: "Aço Reforçado / Alumínio",
    grade: "Profissional",
    application: "Injeção de cartuchos de ancoragem química bi-componentes sem esforço excessivo.",
    description: "Aplicador manual robusto com alta taxa de transmissão de força mecânica para resinas viscosas.",
    sizes: ["Aplicador 300ml", "Aplicador coaxial 410ml", "Aplicador side-by-side 390ml"],
    image: "/produtos/chumbadores quimicos/image9.jpeg",
  },
  {
    id: "quimico-10",
    category: 4,
    title: "Limpador de Furo",
    norm: "Procedimento Técnico de Ancoragem",
    material: "Aço e Cerdas de Nylon / Soprador de Borracha",
    grade: "Ferramenta de Limpeza",
    application: "Limpeza mecânica de furos para remoção de pó de concreto antes de aplicar a resina.",
    description: "Escovas cilíndricas de aço e sopradores manuais de alta vazão para garantir a perfeita aderência química.",
    sizes: ["Escovas M8 a M24", "Soprador Manual standard"],
    image: "/produtos/chumbadores quimicos/image10.jpeg",
  },
  // Categoria 5: Rebites
  {
    id: "rebite-1",
    category: 5,
    title: "Rebite de Repuxo",
    norm: "DIN 7337",
    material: "Alumínio / Aço Carbono / Inox",
    grade: "Grau Industrial",
    application: "União rápida de chapas finas, perfis, esquadrias e gabinetes de metal.",
    description: "Rebite cego de repuxo padrão com corpo de alumínio e mandril de aço.",
    sizes: ["2.4 x 6mm", "3.2 x 8mm", "4.0 x 10mm", "4.8 x 12mm", "4.8 x 19mm", "6.4 x 25mm"],
    image: "/produtos/rebite/image1.jpeg",
  },
  {
    id: "rebite-2",
    category: 5,
    title: "Porca Rebite",
    norm: "Norma Técnica Rosca Cega",
    material: "Aço Carbono Zincado / Inox",
    grade: "Grau 8 / Rosca Forte",
    application: "Criação de rosca interna forte em chapas metálicas de pouca espessura onde não cabe rosca convencional.",
    description: "Elemento de fixação que atua como rebite de repuxo e deixa uma rosca interna funcional.",
    sizes: ["M4", "M5", "M6", "M8", "M10", "M12"],
    image: "/produtos/rebite/image2.jpeg",
  },
  {
    id: "rebite-3",
    category: 5,
    title: "Rebite Maciço",
    norm: "DIN 660 / DIN 661",
    material: "Aço Carbono / Alumínio / Latão / Cobre",
    grade: "Dúctil para conformação",
    application: "Estruturas de pontes, caldeiraria pesada, panelas e cutelaria.",
    description: "Rebite clássico sem furos que requer rebatimento mecânico ou pneumático das extremidades.",
    sizes: ["3/32\"", "1/8\"", "5/32\"", "3/16\"", "1/4\"", "5/16\"", "3/8\""],
    image: "/produtos/rebite/image3.jpeg",
  },
  {
    id: "rebite-4",
    category: 5,
    title: "Rebite Semi Tubular",
    norm: "DIN 7340",
    material: "Aço Carbono / Latão / Alumínio",
    grade: "Leve",
    application: "Montagens de lonas de freio, autopeças, fichários, pastas e artigos de couro.",
    description: "Possui extremidade parcialmente oca para facilitar o rebatimento com menor aplicação de força mecânica.",
    sizes: ["M3", "M4", "M5", "M6", "M8"],
    image: "/produtos/rebite/image4.jpeg",
  },
  {
    id: "rebite-5",
    category: 5,
    title: "Rebite Escalonado",
    norm: "Norma Interna de Articulação",
    material: "Aço Baixo Carbono Zincado",
    grade: "Mecânica",
    application: "Dobradiças de escadas de alumínio, articulações de portões e móveis dobráveis.",
    description: "Rebite com corpo de diâmetro duplo (degrau) projetado para servir como eixo em articulações mecânicas móveis.",
    sizes: ["Diâmetros sob consulta e especificações técnicas"],
    image: "/produtos/rebite/image5.jpeg",
  },
  {
    id: "rebite-6",
    category: 5,
    title: "Rebite Tipo U",
    norm: "Padrão de Fixação de Placas",
    material: "Aço Carbono Cementado / Temperado",
    grade: "Alta Dureza",
    application: "Fixação de plaquetas de identificação de motores, bombas industriais e chassis.",
    description: "Possui estrias helicoidais acentuadas na haste que rosqueiam no furo sob impacto, travando permanentemente.",
    sizes: ["#2 x 3/16\"", "#4 x 1/4\"", "#6 x 3/8\""],
    image: "/produtos/rebite/image6.jpeg",
  },

  // Categoria 7: Acessórios e Fixadores
  {
    id: "acessorio-1",
    category: 7,
    title: "Porca Olhal",
    norm: "DIN 582",
    material: "Aço Carbono / Inox",
    grade: "Grau C15E / Inox A2",
    application: "Pontos de ancoragem suspensa, elevação de motores, geradores, painéis e máquinas pesadas.",
    description: "Porca sextavada com anel olhal integrado para içamento de cargas.",
    sizes: ["M8", "M10", "M12", "M16", "M20", "M24", "M30"],
    image: "/produtos/acessórios/image1.jpeg",
  },
  {
    id: "acessorio-2",
    category: 7,
    title: "Parafuso Olhal",
    norm: "DIN 580",
    material: "Aço Carbono / Inox",
    grade: "Grau C15E",
    application: "Pontos de içamento fixados em carcaças de motores e redutores.",
    description: "Parafuso com cabeça em formato de anel circular para engate de ganchos e cabos.",
    sizes: ["M8", "M10", "M12", "M16", "M20", "M24", "M30"],
    image: "/produtos/acessórios/image2.jpeg",
  },
  {
    id: "acessorio-3",
    category: 7,
    title: "Esticador Gancho Olhal",
    norm: "DIN 1480",
    material: "Aço Carbono Galvanizado / Inox",
    grade: "Comercial / Alta Capacidade",
    application: "Tensionamento de cabos de aço, cordas, arames e sistemas de amarração de cargas.",
    description: "Corpo central ajustável por rosca com pontas tipo gancho e tipo olhal nas extremidades.",
    sizes: ["3/16\"", "1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/acessórios/image3.jpeg",
  },
  {
    id: "acessorio-4",
    category: 7,
    title: "Sapatilha",
    norm: "DIN 6899 Forma B",
    material: "Aço Carbono Galvanizado / Inox",
    grade: "Leve / Pesada",
    application: "Proteção de laços de cabos de aço contra desgaste e dobras acentuadas nos pontos de engate.",
    description: "Acessório em formato de gota com canaleta para alojar perfeitamente o cabo de aço.",
    sizes: ["1/8\"", "3/16\"", "1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/acessórios/image4.jpeg",
  },
  {
    id: "acessorio-5",
    category: 7,
    title: "Mosquetão",
    norm: "DIN 5299 Forma C",
    material: "Aço Carbono Zincado / Inox A4",
    grade: "Segurança / Uso Geral",
    application: "Conexões rápidas de cabos, correntes, cordas, equipamentos esportivos e industriais.",
    description: "Mosquetão com trava de mola de engate rápido e simples.",
    sizes: ["4x40mm", "5x50mm", "6x60mm", "8x80mm", "10x100mm", "12x140mm"],
    image: "/produtos/acessórios/image5.jpeg",
  },
  {
    id: "acessorio-6",
    category: 7,
    title: "Manilha Reta",
    norm: "DIN 82101 / US FED SPEC RR-C-271",
    material: "Aço Carbono / Inox / Pinos de Liga",
    grade: "Grau 80 / Grau 6",
    application: "Uniões de cabos de aço, correntes e cintas de elevação sob tração reta em guindastes e reboques.",
    description: "Manilha reta em formato 'D' com pino rosqueado de segurança.",
    sizes: ["3/16\"", "1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\"", "7/8\"", "1\""],
    image: "/produtos/acessórios/image6.jpeg",
  },
  {
    id: "acessorio-7",
    category: 7,
    title: "Manilha Curva",
    norm: "US FED SPEC RR-C-271 (Alça Curva)",
    material: "Aço Carbono Forjado com Pino Liga",
    grade: "Grau 80 / Alta Capacidade",
    application: "Içamentos de cargas multidirecionais e amarrações de alta carga.",
    description: "Manilha curva em formato de ômega (lira) que permite maior liberdade angular nos laços.",
    sizes: ["1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\"", "7/8\"", "1\"", "1.1/4\""],
    image: "/produtos/acessórios/image7.jpeg",
  },
  {
    id: "acessorio-8",
    category: 7,
    title: "Clip",
    norm: "DIN 741 / DIN 1142",
    material: "Aço Carbono Galvanizado / Inox A4",
    grade: "Comercial / Segurança",
    application: "Confecção de olhais e extremidades de cabos de aço por prensagem de porcas.",
    description: "Grampo clipes em formato 'U' com base de aperto serrilhada e porcas sextavadas.",
    sizes: ["1/8\"", "3/16\"", "1/4\"", "5/16\"", "3/8\"", "1/2\"", "5/8\"", "3/4\""],
    image: "/produtos/acessórios/image8.jpeg",
  },
  {
    id: "acessorio-9",
    category: 7,
    title: "Gancho com Rosca para Bucha e Madeira",
    norm: "Norma Comercial",
    material: "Aço Carbono Zincado",
    grade: "Leve",
    application: "Fixação e sustentação suspensa de vasos, varais de teto e decorações leves em madeira ou bucha plástica em alvenaria.",
    description: "Gancho curvado aberto com rosca soberba autocortante.",
    sizes: ["#17 x 50", "#19 x 60", "#21 x 70", "#22 x 80"],
    image: "/produtos/acessórios 2/image1.jpeg",
  },
  {
    id: "acessorio-10",
    category: 7,
    title: "Pitão com Rosca para Bucha e Madeira",
    norm: "Norma Comercial",
    material: "Aço Carbono Zincado",
    grade: "Leve",
    application: "Pontos de fixação fechados para cabos, cordas e redes de proteção.",
    description: "Parafuso pitão com olhal circular fechado e rosca soberba.",
    sizes: ["#17 x 50", "#19 x 60", "#21 x 70", "#22 x 80"],
    image: "/produtos/acessórios 2/image2.jpeg",
  },
  {
    id: "acessorio-11",
    category: 7,
    title: "Escápula com Rosca para Bucha e Madeira",
    norm: "Norma Comercial",
    material: "Aço Carbono Zincado",
    grade: "Leve",
    application: "Fixação suspensa de quadros, espelhos, varais e armários leves em madeira ou paredes com bucha de nylon.",
    description: "Gancho em formato de 'L' ângulo de 90 graus com rosca soberba.",
    sizes: ["#17 x 50", "#19 x 60", "#21 x 70", "#22 x 80"],
    image: "/produtos/acessórios 2/image3.jpeg",
  },
  {
    id: "acessorio-12",
    category: 7,
    title: "Pino Elástico",
    norm: "DIN 1481 / ISO 8752",
    material: "Aço Mola de Alta Carbono",
    grade: "Mola Temperada",
    application: "Travamento e fixação mecânica de eixos móveis, polias, engrenagens e articulações industriais.",
    description: "Pino cilíndrico oco fendido longitudinalmente que se expande radialmente exercendo pressão contra as paredes do furo.",
    sizes: ["M2", "M3", "M4", "M5", "M6", "M8", "M10", "M12"],
    image: "/produtos/acessórios 2/image4.jpeg",
  },
  {
    id: "acessorio-13",
    category: 7,
    title: "Contrapino",
    norm: "DIN 94 / ISO 1234",
    material: "Aço Baixo Carbono Zincado / Inox A2",
    grade: "Macio (Dúctil)",
    application: "Travamento de porcas castelo sem e com coroa em eixos roscados e pinos de articulação.",
    description: "Pino de metal dobrado (cupilha) com duas hastes flexíveis para dobramento manual após inserção no furo.",
    sizes: ["1/16\"", "3/32\"", "1/8\"", "5/32\"", "3/16\"", "1/4\"", "M1.6", "M2", "M3.2", "M4", "M5", "M6.3"],
    image: "/produtos/acessórios 2/image5.jpeg",
  },
  // Categoria 6: Fixadores Para Painéis Solares
  {
    id: "solar-1",
    category: 6,
    title: "Porca Sextavada (Flangeada Serrilhada)",
    norm: "DIN 6923 Serrilhada / Inox A2-70",
    material: "Aço Inox A2 / Aço Carbono Zincado",
    grade: "Classe 8 / Inox A2",
    application: "Fixação e aterramento de estruturas e trilhos de alumínio para painéis solares fotovoltaicos.",
    description: "Serrilhas auto-travantes sob a flange garantem travamento contra vibrações de vento e conexão elétrica de aterramento.",
    sizes: ["M8", "M10", "M12"],
    image: "/produtos/porca_sextavada_-flangeada_serrilhada-.png",
  },
  {
    id: "solar-2",
    category: 6,
    title: "Parafuso Francês",
    norm: "DIN 603 / ASME B18.5",
    material: "Aço Inox A2 / Aço Carbono Galvanizado",
    grade: "Classe 8.8 / Inox A2",
    application: "Fixação de ganchos de telha, suportes de alvenaria e estruturas de fixação solar.",
    description: "Cabeça cogumelo com pescoço quadrado anti-giro para montagem rápida em perfis e suportes solares.",
    sizes: ["M8", "M10", "M12", "5/16\"", "3/8\""],
    image: "/produtos/parafuso-frances.jpeg",
  },
  {
    id: "solar-3",
    category: 6,
    title: "Parafuso Allen (Sextavado Interno)",
    norm: "DIN 912 / ISO 4762",
    material: "Aço Inox A2-70 / Aço Liga",
    grade: "Inox A2 / Classe 12.9",
    application: "Fixação de grampos intermediários (mid clamps) e grampos terminais (end clamps) em módulos fotovoltaicos.",
    description: "Cabeça cilíndrica com sextavado interno para aperto rápido com chave Allen em espaços reduzidos de trilhos.",
    sizes: ["M6", "M8", "M10"],
    image: "/produtos/parafuso_sextavado_interno_-cabeca_cilindrica-.jpeg",
  },
  {
    id: "solar-4",
    category: 6,
    title: "Parafuso Martelo (Parafuso T)",
    norm: "DIN 2874 / Padrão Solar Fotovoltaico",
    material: "Aço Inox A2 / Aço Carbono Galvanizado",
    grade: "Inox A2 / Classe 8.8",
    application: "Encaixe e travamento rápido em canais de perfis de alumínio para fixação de estruturas de painéis solares.",
    description: "Cabeça tipo martelo/T que gira 90 graus dentro da ranhura do perfil de alumínio proporcionando travamento firme.",
    sizes: ["M8", "M10"],
    image: "/produtos/parafuso_martelo.webp",
  },
  {
    id: "solar-5",
    category: 6,
    title: "Hastes Roscadas / Prisioneiros Solares",
    norm: "DIN 975 / DIN 976 / ISO 3506",
    material: "Aço Inox A2 / Aço Carbono Galvanizado a Fogo",
    grade: "Inox A2-70 / Classe 8.8",
    application: "Ancoragem em telhados de madeira, estrutura metálica e lajes para sustentação de trilhos solares.",
    description: "Hastes de rosca dupla/soberba com vedação em borracha EPDM para fixação estanque de estruturas fotovoltaicas.",
    sizes: ["M8 x 200mm", "M10 x 200mm", "M10 x 250mm", "M12 x 300mm"],
    image: "/produtos/haste-solar.webp",
  },
];

